### ISSUE TITLE
Documentation incorrect

### ISSUE THREAD

**Issue by timjong93** [matiassingers/ipa-metadata#6]
Hello it appears your documentation has one little error in it.
The callback should actually contain two parameters eg. error and data.

```
ipaMetadata('Facebook.ipa', function(data){
  console.log(data);

  // { metadata: 
  //    { CFBundleName: 'Facebook',
  //      ... },
  //   provisioning:
  //    { TeamName: 'Facebook Inc.',
  //      ... } },
  //   entitlements:
  //    { application-identifier: '1234abcd.com.facebook.facebook.',
  //      ... } }
});
```

**Comment by matiassingers** [comment]
Correct, good catch! :+1:

**Comment by matiassingers** [comment]
Fixed in https://github.com/matiassingers/ipa-metadata/commit/1fa3f3f6976e096359de9a6a0349444d8df7735b.

Thanks again @timjong93
