### ISSUE TITLE
Uniform field names

### ISSUE THREAD

**Issue by timjong93** [matiassingers/ipa-metadata#7]
Hello me again,

Thanks for the amazingly quick fix on the documentation error, using this project i have found some little inconsistencies which might be handy to address.
Most fieldnames in the returned data object are written in cammelCase. Although some (for example: **data.provisioning.Entitlements.application-identifier**) contain dashes.

This makes them more difficult to call because you have to use something like:
```
var x = data.provisioning.Entitlements['application-identifier'];
```

I don't know if this is a design choice because of the names used in the mobileprovisioning file or not but it might be something you want to to take a look at.

**Comment by matiassingers** [comment]
@timjong93 yeah my slight OCD was also extremely annoyed by the inconsistency in naming conventions.

I however preserved the original namings from the mobileprovisioning, entitlements etc.

Might be worth looking into standardizing them all as camelCase, I'm just afraid people might get confused if they are looking for the specific key `application-identifier` from their entitlements.

What do you think?

**Comment by timjong93** [comment]
It might be better for usability, i personally didn't know the fieldnames from for example mobileprovisioning so i looked at the returned data object and worked my way from there. In my case it wouldn't matter. But i can understand that it would confuse people.

Don't know what the best solution is but i tend to just keeping it this way if these are the actual names in the original files.

**Comment by matiassingers** [comment]
Added a note to the README about lack of naming conventions: https://github.com/matiassingers/ipa-metadata/commit/c822b07eab591da4c3c717a820f3e2527f1558c8
