### ISSUE TITLE
Only usable on MacOS

### ISSUE THREAD

**Issue by timjong93** [matiassingers/ipa-metadata#8]
Due tot he fact that this uses the provisioning module which uses the shell command:

```
security cms -D -i
```

This is only usable on Mac OS devices. Running it on other operating systems will result in a security not found error. This should at least be noted in the documentation but preferably be changed in a way it is cross platform compatible

**Comment by matiassingers** [comment]
Good point, I should add a note about it to the README.

@katunch actually attempted to fix this, but I'm not sure if he every split out the logic into a separate module. See https://github.com/matiassingers/ipa-metadata/pull/3
